### ISSUE TITLE
Exported pages are sometimes duplicated

### ISSUE THREAD

**Issue by NontasBak** [kitschpatrol/tldraw-cli#11]
So I have this weird bug that duplicates the first page of the .tldr file when exporting to .png, replacing the .png of the 2nd page. Basically instead of exporting `page1, page2` it exports `page1, page1`

I've noticed that this occurs when I modify the last page of a .tldr file while also leaving the rest of the pages untouched. If I modify the 1st page in some way the glitch stops occurring.

I'll send the buggy .tldr file so you can test yourself, the command I used is `tldraw export 2022-june.tldr --format png --pages`
[2022-june.zip](https://github.com/user-attachments/files/15945405/2022-june.zip)

**Comment by kitschpatrol** [comment]
Hi Nontas, ah that's interesting, thanks for reporting.

I am able reproduce this bug with the file you provided, and will dig into it within the next few days.

**Comment by kitschpatrol** [comment]
This was due to a logic error in my page-handling code. 🤦‍♂️

Should be fixed in [v4.6.5](https://github.com/kitschpatrol/tldraw-cli/releases/tag/v4.6.5), let me know if it's a fix for you.

Thanks again for spotting this.

**Comment by NontasBak** [comment]
Thanks for the update! Works perfectly on my end 👌
